In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
from word2number import w2n

In [2]:
emp_data = pd.read_csv('hiring.csv')
emp_data

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [3]:
emp_data.experience.fillna('Zero',inplace=True)
emp_data

experience  test_score  interview_score  salary
0       Zero         8.0                9   50000
1       Zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [4]:
median_testscore = emp_data.test_score.median()
median_testscore

8.0

In [5]:
emp_data.test_score.fillna(median_testscore,inplace=True)
emp_data

experience  test_score  interview_score  salary
0       Zero         8.0                9   50000
1       Zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [6]:
emp_data['num_experience'] = emp_data.experience.apply(w2n.word_to_num)
emp_data

experience  test_score  interview_score  salary  num_experience
0       Zero         8.0                9   50000               0
1       Zero         8.0                6   45000               0
2       five         6.0                7   60000               5
3        two        10.0               10   65000               2
4      seven         9.0                6   70000               7
5      three         7.0               10   62000               3
6        ten         8.0                7   72000              10
7     eleven         7.0                8   80000              11

In [7]:
reg = linear_model.LinearRegression()

In [8]:
reg.fit(emp_data[['num_experience','test_score','interview_score']],emp_data.salary)

LinearRegression()

In [9]:
print(reg.coef_)
print(reg.intercept_)

[2812.95487627 1845.70596798 2205.24017467]
17737.26346433771


In [11]:
reg.predict([[0,8,9]])

array([52350.0727802])

In [12]:
df2 = emp_data[['num_experience','test_score','interview_score']]
df2

num_experience  test_score  interview_score
0               0         8.0                9
1               0         8.0                6
2               5         6.0                7
3               2        10.0               10
4               7         9.0                6
5               3         7.0               10
6              10         8.0                7
7              11         7.0                8

In [13]:
predict_salary = reg.predict(df2)
predict_salary

array([52350.0727802 , 45734.35225619, 58312.95487627, 63872.63464338,
       67270.74235808, 61148.47161572, 76069.1411936 , 79241.63027656])

In [14]:
emp_data['predict_salary'] = predict_salary

In [15]:
emp_data

experience  test_score  interview_score  salary  num_experience  \
0       Zero         8.0                9   50000               0   
1       Zero         8.0                6   45000               0   
2       five         6.0                7   60000               5   
3        two        10.0               10   65000               2   
4      seven         9.0                6   70000               7   
5      three         7.0               10   62000               3   
6        ten         8.0                7   72000              10   
7     eleven         7.0                8   80000              11   

   predict_salary  
0    52350.072780  
1    45734.352256  
2    58312.954876  
3    63872.634643  
4    67270.742358  
5    61148.471616  
6    76069.141194  
7    79241.630277